In [2]:
'''4.2 Machine Learning - Medium
•Riddle Id:
ml medium
•Problem Statement:
In machine learning, connected components refer to sets of vertices in a graph that are
connected to each other through edges but not connected to vertices outside the group.
They are used to identify clusters or sub-graphs of nodes that are interconnected within
a graph. In the field of network security, identifying connected components can help in
understanding the structure of a network, detecting isolated or vulnerable components.
Your task is: detecting connected components using machine learning algorithms, you
have a complex connected shape surrounded by groups of points. Machine Learning
algorithms such as classification, clustering is helpful to map points based on their fea-
tures to either belonging to the shape or not. You need to use your skills to map the
point to the correct group. Your training data can be found in the received materials,
and consists of two features representing the x and y coordinates, and the label that has
values either 0 for connected shape, and -1 for a point that doesn’t belong to the shape.
•Input Description:
The input is a NumPy array for the (x, y) coordinates of the point.
•Expected Output:
The expected output is an integer either 0 for the shape or -1 for any point that
doesn’t belong to the connected component.
•Example:
Input = (0,0)
Predicted label = -1
•Evaluation:
We will compare your classified label with the actual label from our end.
•Acceptance Criteria:
You will be rewarded if you get the same group as expected, since this is a classifica-
tion problem, there is no margin of error.'''

'4.2 Machine Learning - Medium\n•Riddle Id:\nml medium\n•Problem Statement:\nIn machine learning, connected components refer to sets of vertices in a graph that are\nconnected to each other through edges but not connected to vertices outside the group.\nThey are used to identify clusters or sub-graphs of nodes that are interconnected within\na graph. In the field of network security, identifying connected components can help in\nunderstanding the structure of a network, detecting isolated or vulnerable components.\nYour task is: detecting connected components using machine learning algorithms, you\nhave a complex connected shape surrounded by groups of points. Machine Learning\nalgorithms such as classification, clustering is helpful to map points based on their fea-\ntures to either belonging to the shape or not. You need to use your skills to map the\npoint to the correct group. Your training data can be found in the received materials,\nand consists of two features representing the 

In [17]:
import re

import nltk 
from nltk import word_tokenize

from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score
from torch.utils.data import Dataset
from torch.utils.data import DataLoader
from torch.utils.data import random_split
from gensim.models import Word2Vec
import tensorflow as tf

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Bidirectional, LSTM, Dense,Embedding

import gensim
from gensim.models import Word2Vec
import numpy as np

from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Concatenate, Dense, LSTM, Embedding, Bidirectional



nltk.download('punkt')
import pandas as pd
from sklearn.model_selection import train_test_split

from keras.models import Sequential
from keras.layers import LSTM, Dense

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\sohad\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [19]:
from sklearn.metrics import mean_squared_error

df = pd.read_csv("MlMediumTrainingData.csv")
X = df[['x_', 'y_']] 
y = df['class']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


X_train_lstm = X_train.values.reshape((X_train.shape[0], 1, X_train.shape[1]))
X_test_lstm = X_test.values.reshape((X_test.shape[0], 1, X_test.shape[1]))

lstm_model = Sequential()
lstm_model.add(LSTM(units=255, input_shape=(X_train_lstm.shape[1], X_train_lstm.shape[2])))
lstm_model.add(Dense(255, activation='relu'))  
lstm_model.add(Dense(1, activation='tanh')) 

lstm_model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
lstm_model.fit(X_train_lstm, np.array(y_train), epochs=10, batch_size=32)
y_pred_lstm = lstm_model.predict(X_test_lstm)

mse = mean_squared_error(y_test, y_pred_lstm)

rmse = np.sqrt(mse)

print("Root Mean Squared Error:", rmse)


Epoch 1/10
51/51 [==============================] - 3s 6ms/step - loss: -0.0459 - accuracy: 0.9969
Epoch 2/10
51/51 [==============================] - 0s 5ms/step - loss: -0.0473 - accuracy: 0.9969
Epoch 3/10
51/51 [==============================] - 0s 5ms/step - loss: -0.0473 - accuracy: 0.9969
Epoch 4/10
51/51 [==============================] - 0s 6ms/step - loss: -0.0473 - accuracy: 0.9969
Epoch 5/10
51/51 [==============================] - 0s 5ms/step - loss: -0.0473 - accuracy: 0.9969
Epoch 6/10
51/51 [==============================] - 0s 6ms/step - loss: -0.0473 - accuracy: 0.9969
Epoch 7/10
51/51 [==============================] - 0s 5ms/step - loss: -0.0473 - accuracy: 0.9969
Epoch 8/10
51/51 [==============================] - 0s 6ms/step - loss: -0.0473 - accuracy: 0.9969
Epoch 9/10
51/51 [==============================] - 0s 5ms/step - loss: -0.0473 - accuracy: 0.9969
Epoch 10/10
13/13 [==============================] - 0s 2ms/step
Root Mean Squared Error: 0.7735726473642162


In [3]:
lstm_model.save("riddle_ml_medium")

INFO:tensorflow:Assets written to: riddle_ml_medium\assets


INFO:tensorflow:Assets written to: riddle_ml_medium\assets


In [4]:
loaded_model = tf.keras.models.load_model("riddle_ml_medium")

In [87]:
print(y_pred_lstm)

[[-0.5025146 ]
 [-0.23499724]
 [-0.30973384]
 [-0.25317803]
 [-0.29275125]
 [-0.18313237]
 [-0.22692463]
 [-0.63058823]
 [-0.61400646]
 [-0.6075335 ]
 [-0.21577376]
 [-0.13033022]
 [-0.5304453 ]
 [-0.26112604]
 [-0.26438692]
 [-0.45288065]
 [-0.26441664]
 [-0.54261136]
 [-0.4182305 ]
 [-0.09421061]
 [-0.6329261 ]
 [-0.3900765 ]
 [-0.5127411 ]
 [-0.3313917 ]
 [-0.3326562 ]
 [-0.6043275 ]
 [-0.6440885 ]
 [-0.4009231 ]
 [-0.6113919 ]
 [-0.4089304 ]
 [-0.605814  ]
 [-0.3493459 ]
 [-0.64518225]
 [-0.64812106]
 [-0.5299944 ]
 [-0.258902  ]
 [-0.47595638]
 [-0.5789683 ]
 [-0.5517808 ]
 [-0.5316027 ]
 [-0.19838563]
 [-0.29706642]
 [-0.6077778 ]
 [-0.522183  ]
 [-0.6371962 ]
 [-0.22425582]
 [-0.09754737]
 [-0.25641546]
 [-0.30616578]
 [-0.52888113]
 [-0.62968   ]
 [-0.26125714]
 [-0.27154464]
 [-0.2760792 ]
 [-0.23111865]
 [-0.51941437]
 [-0.13652301]
 [-0.4033788 ]
 [-0.30784395]
 [-0.6322222 ]
 [-0.5471079 ]
 [-0.64463794]
 [-0.31846765]
 [-0.28405812]
 [-0.5026522 ]
 [-0.21892187]
 [-0.31274

In [16]:
input_array = [12.78298128,2.062236795]
input_array = np.array(input_array)

input_lstm = input_array.reshape((1, 1, len(input_array)))
prediction = lstm_model.predict(input_lstm)

print(prediction)
rounded_prediction = np.round(prediction)

predicted_class = int(rounded_prediction[0][0])   
print(predicted_class)

1/1 [==============================] - 0s 28ms/step
[[-0.818675]]
-1


In [97]:
numpy_carrier_image = [[2, 3, 23], [4, 5, 68], [6, 8, 12]]
carrier_image = np.array(numpy_carrier_image)
print( np.array(carrier_image))

[[ 2  3 23]
 [ 4  5 68]
 [ 6  8 12]]


In [99]:
arrayee=['','','']
arrayee[0]=numpy_carrier_image=[2,3,4]
print( arrayee)

[[2, 3, 4], '', '']
